package com.transferwise.spyql

import spock.lang.Specification

class StatementInvocationHandlerTest extends Specification {
	def "executeQuery(String sql)"() {
		expect:
		false
	}
	def "executeUpdate(String sql)"() {
		expect:
		false
	}
	def "execute(String sql)"() {
		expect:
		false
	}
	def "executeBatch()"() {
		expect:
		false
	}
	def "executeUpdate(String sql, int autoGeneratedKeys)"() {
		expect:
		false
	}
	def "executeUpdate(String sql, int[] columnIndexes)"() {
		expect:
		false
	}
	def "executeUpdate(String sql, String[] columnNames)"() {
		expect:
		false
	}
	def "execute(String sql, int autoGeneratedKeys)"() {
		expect:
		false
	}
	def "execute(String sql, int[] columnIndexes)"() {
		expect:
		false
	}
	def "execute(String sql, String[] columnNames)"() {
		expect:
		false
	}
	def "executeLargeBatch()"() {
		expect:
		false
	}
	def "executeLargeUpdate(String sql)"() {
		expect:
		false
	}
	def "executeLargeUpdate(String sql, int autoGeneratedKeys)"() {
		expect:
		false
	}
	def "executeLargeUpdate(String sql, int[] columnIndexes)"() {
		expect:
		false
	}
	def "executeLargeUpdate(String sql, String[] columnNames)"() {
		expect:
		false
	}
}
